### ISSUE TITLE
I got error "unknown tag !<!Ref:> "

### ISSUE THREAD

**Issue by balazsnemeth** [henhal/serverless-plugin-layer-manager#1]
My layer is setup as you described, but referencing like:

```
functions:
  getSoftskillScore:
    handler: handler.getSoftSkillScore
    layers:
      - !Ref: CommonLibsLambdaLayer
```

Throws the error:

unknown tag !<!Ref:> in "/Users/nbalazs/Work/awesomeprojects/serverless.yml" at line 45, column 36:
            - !Ref: CommonLibsLambdaLayer
